/* ----------------- This File Saves Request from Homepage ----------------- */
/* ----------------- Created : 27-4-2021 by Prayag ----------------- */
/* -------------------------------------------------- Requirements -------------------------------------------------- */
const mongoose = require("mongoose");
const nodemailer = require('nodemailer');
const moment = require('moment');
const { google } = require('googleapis');
/* -------------------------------------------------- Requirements -------------------------------------------------- */


/* -------------------------------------------------- Sending Email Credentials -------------------------------------------------- */
const CLIENT_ID = '168438088579-d77o04co2nb75sbgqf8lmc1jh01aaiki.apps.googleusercontent.com';
const CLEINT_SECRET = 'Uq2NNmcKr6uR1LyCZ-zvK4r3';
const REDIRECT_URI = 'https://developers.google.com/oauthplayground';
const REFRESH_TOKEN = '1//04cQGDkJNePgMCgYIARAAGAQSNwF-L9Ir7VTRMwbgzqwq2-5nuL-sQNDSlBKhNekIqgBHvvR743sAX6BeTOU5UpmcTrbTGJGTjQs';
const oAuth2Client = new google.auth.OAuth2(
    CLIENT_ID,
    CLEINT_SECRET,
    REDIRECT_URI
  );
  oAuth2Client.setCredentials({ refresh_token: REFRESH_TOKEN });
/* -------------------------------------------------- Sending Email Credentials -------------------------------------------------- */
  


/* -------------------------------------------------- Schemas -------------------------------------------------- */
const RequestsSchema = require("../../../models/requests-schema");
const userSchema = require('../../../models/user-schema');
const patientSchema = require('../../../models/patient-info-schema');

/* ------------------------------------------------------------------------------------------------------------------ */

module.exports = {
    // Create new request
    // 27-4-2021 Prayag
    CreateRequest: async (req, res) => {
        try {
            const { name, mobile, pincode, surgery, treatment, referal, amount, reason, type, rfor } = req.body;

            var emaildate = moment(new Date()).format("DD/MM/YYYY h:mm");

            // Save Request
            const saverequest = new RequestsSchema({
                name: name,
                mobile: mobile,
                pincode: pincode,
                type: type,
                surgery: surgery,
                treatment: treatment,
                referal: referal,
                for: rfor,
                amount: amount,
                reason: reason,
            });
            const savedRequestDetails = await saverequest.save();


            if (type === 'estimation') {
                var emailcontent = '\nName : ' + name + '\nMobile : ' + mobile + '\nPincode : ' + pincode + '\nType : ' + type + '\nTreatment : ' + treatment;
            }
            else if (type === 'surgery') {
                var emailcontent = '\nName : ' + name + '\nMobile : ' + mobile + '\nPincode : ' + pincode + '\nType : ' + type + '\nSurgery : ' + surgery;
            }
            else if (type === 'easyloan') {
                var emailcontent = '\nName : ' + name + '\nMobile : ' + mobile + '\nPincode : ' + pincode + '\nType : ' + type + '\nLoan Amount : ' + amount + '\nReason : ' + reason;                
            }
            else {
                var emailcontent = '\nName : ' + name + '\nMobile : ' + mobile + '\nPincode : ' + pincode + '\nType : ' + type + '\nReferral Name : ' + referal + '\nFor : ' + rfor;                
            }

            const accessToken = await oAuth2Client.getAccessToken();
            const transport = nodemailer.createTransport({
                service: 'gmail',
                auth: {
                  type: 'OAuth2',
                  user: 'info@easyaspataal.com',
                  clientId: CLIENT_ID,
                  clientSecret: CLEINT_SECRET,
                  refreshToken: REFRESH_TOKEN,
                  accessToken: accessToken,
                },
              });
                      
              const mailOptions = {
                from: 'info@easyaspataal.com',
                to: 'info@easyaspataal.com',
				subject: '[' + type + '] Request by ' + name + ' on ' + emaildate,
				text: 'We have received a request: The details are as follows: \n' + emailcontent + '\n\nThis email has been generated by a bot.'
                // html: '<h1>Hello from gmail email using API</h1>',
              };
          
			transport.sendMail(mailOptions, function (error, info) {
				if (error) {
					console.log(error);
				} else {
					console.log('Email sent: ' + info.response);
				}
			});
            res.json('Success')
        } catch (error) {
            console.log(error);
        }
    },
};
